name: eslint

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  lint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . # Adjust the command based on your ESLint setup
